deployment:
  containerApiPort: 29191
  containerControlPort: 29192
  containerManagementPort: 29193
  containerProtocolPort: 29194
  containerPublicPort: 29291
  label: consumer

service:
  apiPort: 29191
  controlPort: 29192
  managementPort: 29193
  protocolPort: 29194
  publicPort: 29291

ingress:
  tlsSecretName: consumer-simpl-backend-tls

# it would be better to move those to vault in the future or use sops encryption
env:
  edcParticipantId: "consumer"
  edcIdsId: "urn:connector:consumer"

postgresql:
  username: edc
