#values:
#  repo_URL: https://code.europa.eu/simpl/simpl-open/development/agents/consumer.git
#  branch: v1.3.0
values:
  repo_URL: https://github.com/FusionArtechSimplOpen/consumer.git
  branch: main

project: ${PROJECT}
namespaceTag: ${NAMESPACETAG}
domainSuffix: ${DOMAINSUFFIX}

argocd:
  appname: ${NAMESPACE}
  namespace: argocd

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  commonToolsNamespace: ${COMMONNAMESPACE}
  issuer: ${CLUSTERISSUER}

authority:
  namespaceTag: ${AUTHNAMESPACETAG}

hashicorp:
  service: "https://vault.common.domainsuffix"
  secretEngine: ${SECRETENGINE}
  role: ${SECRETROLE}

keycloak:
  repo_URL: https://charts.bitnami.com/bitnami
  chart_name: keycloak
  targetRevision: 22.2.5
  nameOverride: keycloak
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

tier1_gateway:
  projectID: "772"
  targetRevision: 1.3.1
  chart_name: tier1-gateway
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

xfsc_advsearch_be:
  enabled: true
  projectID: "891"
  targetRevision: 1.6.0
  chart_name: xsfc-advsearch
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
  nameOverride: xfsc-advsearch-be

users_roles:
  projectID: "771"
  targetRevision: 1.3.1
  chart_name: users-roles
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

simpl_fe:
  projectID: "769"
  targetRevision: 1.3.5
  chart_name: simpl-fe
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
    - values-participant.yaml

tier2_gateway:
  projectID: "860"
  targetRevision: 1.3.1
  chart_name: tier2-gateway
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
    - values-routes.yaml

simpl_edc:
  enabled: true
  projectID: "920"
  targetRevision: 1.0.3
  chart_name: edc
  nameOverride: simpl-edc
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
    - values-consumer.yaml

simpl_catalogue_client:
  enabled: true
  projectID: "937"
  targetRevision: 1.2.0
  chart_name: catalogue-ui
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

auth_provider:
  projectID: "939"
  targetRevision: 1.3.4
  chart_name: authentication-provider
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

monitoring:
  enabled: true
  projectID: "828"
  targetRevision: 0.1.12
  chart_name: eck-monitoring
  fullnameOverride: elastic
  valueFiles:
    - values.yaml

contract:
  projectID: "872"
  targetRevision: 1.0.3
  chart_name: simpl-contract
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml
  nameOverride: contract-consumer      

stubs:
  projectID: "930"
  targetRevision: 1.0.0
  chart_name: simpl-stubs
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml  

contract_consumption_be:
  enabled: true
  projectID: "968"
  targetRevision: 1.4.0
  chart_name: contract-consumption-be
  nameOverride: contract-consumption-be
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

simpl_cli:
  projectID: "882"
  targetRevision: 1.3.0
  chart_name: simpl-cli
  fullnameOverride: simpl-cli
  valueFiles:
    - values.yaml    
