securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

envFrom:
  - configMapRef:
      name: simpl-cli-configmap

initParticipant:
  enabled: true
  ptype: CONSUMER
  csr:
    country: EU
  keycloak:
    internalPort: 80
    app:
      realm: participant
      clientId: cli
    master:
      realm: master
      user: admin
      clientId: admin-cli
    authority:
      user: admin
      realm: authority
initAuthority:
  enabled: false